// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Repository;

namespace api.Repository.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("api.Domain.Caderno", b =>
                {
                    b.Property<int>("CadernoId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("UsuarioId");

                    b.HasKey("CadernoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Cadernos");
                });

            modelBuilder.Entity("api.Domain.CadernoQuestao", b =>
                {
                    b.Property<int>("CadernoId");

                    b.Property<int>("QuestaoId");

                    b.HasKey("CadernoId", "QuestaoId");

                    b.HasIndex("QuestaoId");

                    b.ToTable("CadernosQuestaos");
                });

            modelBuilder.Entity("api.Domain.Comentario", b =>
                {
                    b.Property<int>("ComentarioId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Assunto");

                    b.Property<DateTime>("Data");

                    b.Property<int>("QuestaoId");

                    b.Property<int>("UsuarioId");

                    b.HasKey("ComentarioId");

                    b.HasIndex("QuestaoId");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("api.Domain.Questao", b =>
                {
                    b.Property<int>("QuestaoId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AlternativaA");

                    b.Property<string>("AlternativaB");

                    b.Property<string>("AlternativaC");

                    b.Property<string>("AlternativaD");

                    b.Property<string>("AlternativaE");

                    b.Property<string>("Ano");

                    b.Property<string>("Assunto");

                    b.Property<string>("Banca");

                    b.Property<string>("ComentarioProfessor");

                    b.Property<string>("Disciplina");

                    b.Property<string>("Enunciado");

                    b.Property<string>("Orgao");

                    b.Property<string>("Resposta");

                    b.HasKey("QuestaoId");

                    b.ToTable("Questaos");
                });

            modelBuilder.Entity("api.Domain.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Email");

                    b.Property<string>("Nome");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Usuario");
                });

            modelBuilder.Entity("api.Domain.Aluno", b =>
                {
                    b.HasBaseType("api.Domain.Usuario");

                    b.Property<string>("Plano");

                    b.HasDiscriminator().HasValue("Aluno");
                });

            modelBuilder.Entity("api.Domain.Professor", b =>
                {
                    b.HasBaseType("api.Domain.Usuario");

                    b.Property<DateTime>("Contratacao");

                    b.HasDiscriminator().HasValue("Professor");
                });

            modelBuilder.Entity("api.Domain.Caderno", b =>
                {
                    b.HasOne("api.Domain.Aluno")
                        .WithMany("Cadernos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("api.Domain.CadernoQuestao", b =>
                {
                    b.HasOne("api.Domain.Caderno", "Caderno")
                        .WithMany("CadernoQuestaos")
                        .HasForeignKey("CadernoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("api.Domain.Questao", "Questao")
                        .WithMany("CadernoQuestaos")
                        .HasForeignKey("QuestaoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("api.Domain.Comentario", b =>
                {
                    b.HasOne("api.Domain.Questao")
                        .WithMany("Comentarios")
                        .HasForeignKey("QuestaoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
